### ISSUE TITLE
readme sample code needs updated

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_CLUE#21]
The example in the readme is using this function `clue.display_clue_data()` but it does not seem to exist any more. [This example from in the repo](https://github.com/adafruit/Adafruit_CircuitPython_CLUE/blob/master/examples/clue_display_sensor_data.py) is essentially the same thing. It's using `clue.simple_text_display()` and it works correctly as far as I can tell. I can work on making a PR to change the readme to match the example script.

**Comment by caternuson** [comment]
Left overs from a function name change. Looks like it also shows up in doc string:
```
Adafruit_CircuitPython_CLUE$ grep -i -r display_clue_data
adafruit_clue.py:        ``clue_data = display_clue_data()`` then ``clue_data[0].text = clue.proximity`` must be
adafruit_clue.py:        .. image :: ../docs/_static/display_clue_data.jpg
README.rst:    clue_data = clue.display_clue_data(title="CLUE Sensor Data!", title_scale=2, num_lines=15)
```

**Comment by FoamyGuy** [comment]
#25 resolves this issue
