### ISSUE TITLE
gesture example not working

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_CLUE#34]
If I run the example from the code (or ReadtheDocs)

```
from adafruit_clue import clue

while True:
    print("Gesture: {}".format(clue.gesture))
```
it just keeps returning 0

FYI - the apds9960_gesture_simpletest works as expected.

**Comment by ladyada** [comment]
hmm we may want to make the simple test a little more advanced where it checks the gesture isnt 0 (which means, none detected) - wnana try that?

**Comment by jerryneedell** [comment]
I tried only reporting if non zero, but then saw nothing.

**Comment by jerryneedell** [comment]
I wonder if the problem is because clue.gesture re_enables gesture every call. Does that “flush”any pending reading. I’ll try to dig deeper later today or tomorrow.

**Comment by jerryneedell** [comment]
simple fix -- "proximity" has to be enabled along with "gesture"  -- I'll put is a PR.
