### ISSUE TITLE
Remove uses of gamepad

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_CLUE#44]
`gamepad` being replaced by `keypad` in CircuitPython 7.0.0. Update this library to use `keypad`.

**Comment by e-simpson** [comment]
I'm also having issue with "gamepad" references on an Adafruit Clue board (nRF52) as I try to get the 7.0.0 alpha running. 
Referenced https://github.com/adafruit/Adafruit_CircuitPython_Bundle/issues/327

**Comment by tekktrik** [comment]
Was perusing the open issues for things to tackle, was this addressed by PR #48 ?

**Comment by FoamyGuy** [comment]
Yes, thanks @tekktrik. 

Closed by #48
