### ISSUE TITLE
sound_level creates a sample buffer every time

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_CLUE#53]
The code checks if `self._sample` has been initialised and then assigns a new buffer to `self._samples` (note plural!). It looks like a typo which wasn't picked up by linting as `_sample` is used for playing sounds over tiny speaker.

https://github.com/adafruit/Adafruit_CircuitPython_CLUE/blob/670355e4b4b4963399ef00702441732b727cdbcc/adafruit_clue.py#L815-L816

This causes a new buffer to be created on each read of the `sound_level` property. This doesn't leak but it is inefficient and may cause problems for applications with a small amount of (fragmented) remaining memory...

---

Once this is fixed, a single read of `sound_level` may be beneficial at the start of a program that's tight on memory or encountering `MemoryError: memory allocation failed, allocating 640 bytes` exceptions later when `sound_level` is used repeatedly. This approach aligns with the advice in [Adafruit Learn: Memory-saving tips for CircuitPython:  Memory: Reducing fragmentation](https://learn.adafruit.com/Memory-saving-tips-for-CircuitPython/reducing-memory-fragmentation).

> Advanced programmers: Allocate a large memory buffer early in the life of your code and reuse the same memory buffer through your program.

**Comment by kevinjwalters** [comment]
Same issue elsewhere: https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/blob/511f55ca17a742a5249540d92fa97e66a4226887/adafruit_circuitplayground/bluefruit.py#L90-L91

I've not done a comprehensive survey on this.

**Comment by tekktrik** [comment]
Looks like this got solved (at least in part) by PR #54, is this fixed now?  Or is it worth specifically calling `gc.collect()` after `self._samples = array.array("H", [0] * 160)`?

**Comment by FoamyGuy** [comment]
I do believe this is resolved by #54. I've submitted a similar fix into the circuitplayground repo and I checked the bundle for any other instances of `self._samples` and found none.
